// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPedidos.DAL;

namespace RegistroPedidos.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201024025029_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("RegistroPedidos.Entidades.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.HasIndex("SuplidorId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.OrdenesDetalle", b =>
                {
                    b.Property<int>("OrdenDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenDetalle");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Inventario")
                        .HasColumnType("REAL");

                    b.Property<int?>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.HasIndex("SuplidorId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 45.5,
                            Descripcion = "galletas",
                            Inventario = 87.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 1000.0,
                            Descripcion = "Fire Ball",
                            Inventario = 53.0
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "Palmares"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombres = " Sazerac Co."
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Ordenes", b =>
                {
                    b.HasOne("RegistroPedidos.Entidades.Suplidores", "suplidores")
                        .WithMany()
                        .HasForeignKey("SuplidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.OrdenesDetalle", b =>
                {
                    b.HasOne("RegistroPedidos.Entidades.Ordenes", null)
                        .WithMany("Detalle")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroPedidos.Entidades.Productos", "productos")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Productos", b =>
                {
                    b.HasOne("RegistroPedidos.Entidades.Productos", null)
                        .WithMany("Detalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroPedidos.Entidades.Suplidores", null)
                        .WithMany("Detalle")
                        .HasForeignKey("SuplidorId");
                });
#pragma warning restore 612, 618
        }
    }
}
